name: Tests

on:
  workflow_dispatch:
  push:
  merge_group:
  pull_request:
    types: [labeled]

env:
  IBMQ_TOKEN: ${{ secrets.IBMQ_TOKEN }}

jobs:
  export_variables:
    runs-on: ubuntu-latest
    steps:
     - name: export
       run: |
         echo "-----------------------> Exporting IBMQ_TOKEN"
         export IBMQ_TOKEN
  build:
    if: contains(github.event.pull_request.labels.*.name, 'run-workflow') || github.event_name == 'push'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9, '3.10', '3.11']
    uses: qiboteam/workflows/.github/workflows/rules-poetry.yml@main
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      poetry-extras: "--with dev"
    secrets: inherit
      
